name: SpringBoot CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Decode application.yml from secret and save it to resources
        run: |
          echo "${{ secrets.APPLICATION_YML }}" | base64 --decode > src/main/resources/application.yml

      - name: Decode keystore.p12 from secret and save to it to resources
        run: |
          echo "${{ secrets.KEYSTORE_P12 }}" | base64 --decode > src/main/resources/keystore.p12
  
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle (bootJar)
        run: ./gradlew bootJar

      - name: Move JAR to Root directory
        run: mv ./build/libs/foodforum-0.0.1.jar ./foodforum-0.0.1.jar

      - name: Upload JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: "foodforum-0.0.1.jar"
          target: "/home/${{ secrets.EC2_USER }}/"

      - name: Stop existing JAR process on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            pid=$(sudo ps aux | grep 'java.*-jar' | grep -v grep | awk '{print $2}')
            if [ -n "$pid" ]; then
              echo "Stopping existing JAR process (PID: $pid)"
              sudo kill -9 $pid
            else
              echo "No running JAR process found."
            fi
            
      - name: Move JAR file and run with nohup
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          port: 22
          script: |
            sudo mv /home/${{ secrets.EC2_USER }}/foodforum-0.0.1.jar /springboot/foodforum-0.0.1.jar
            sudo nohup java -Dspring.profiles.active=prod -jar /springboot/foodforum-0.0.1.jar > /dev/null 2>&1 &
