name: SpringBoot CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build with Gradle (bootJar)
        run: ./gradlew bootJar

      - name: Upload JAR to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}  # EC2 호스트 IP
          username: ${{ secrets.EC2_USER }}  # EC2 사용자
          key: ${{ secrets.EC2_PRIVATE_KEY }}  # EC2 개인 키 (SSH 키)
          port: 22
          script: |
            # EC2 서버에서 JAR 파일을 적절한 경로로 이동 및 실행
            cd /springboot
            rm -f myapp.jar  # 이전 JAR 파일 제거 (옵션)
            mv myapp-*.jar myapp.jar  # 최신 JAR 파일을 myapp.jar로 이동
            nohup java -jar myapp.jar > /dev/null 2>&1 &  # 백그라운드에서 JAR 파일 실행
