name: SpringBoot CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Decode application.yml from secret and save it to resources
        run: |
          echo "${{ secrets.APPLICATION_YML }}" | base64 --decode > src/main/resources/application.yml

      - name: Build with Gradle (bootJar)
        run: ./gradlew bootJar

      # - name: Upload JAR to EC2
      #   uses: appleboy/ssh-action@v0.1.6
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ${{ secrets.EC2_USER }}
      #     key: ${{ secrets.EC2_PRIVATE_KEY }}
      #     port: 22
      #     script: |
      #       cd /springboot
      #       rm -f myapp.jar
      #       mv myapp-*.jar myapp.jar
      #       nohup java -jar myapp.jar > /dev/null 2>&1 &
